### ISSUE TITLE
Support for CRAM submission

### ISSUE THREAD

**Issue by edsu7** [icgc-argo/argo-data-submission#30]

**Comment by edsu7** [comment]
A potential issue is that submitter provides incorrect `md5sum` and `filesize` with `CRAM` file.
Current seq-tools check would miss this  as it only checks the converted `BAM` and not the original `CRAM`. Adding seq-tools check for nested `CRAM` info assuming standardized format.

See https://github.com/icgc-argo/argo-data-submission/issues/40

**Comment by puneet-oicr** [comment]
All tickets closed, Edmund working on documentation

**Comment by b-f-chan** [comment]
Closing, documentation done!
