### ISSUE TITLE
Adjust the default values of the workflow to avoid requesting from users

### ISSUE THREAD

**Issue by lindaxiang** [icgc-argo/argo-data-submission#34]
some default values for
- song_url: https://submission-song.rdpc.cancercollaboratory.org
- score_url: https://submission-score.rdpc.cancercollaboratory.org
- cpus: 2
- mem: 4
- max_retries: 2

**Comment by b-f-chan** [comment]
Leave in backlog unassigned for now, should be quick fix, just do at last minute after the sanity checks added and submission workflow is ready

**Comment by lindaxiang** [comment]
This has been addressed in commit: https://github.com/icgc-argo/argo-data-submission/pull/50/commits/3cd3ace5d0401962982a0eb766bf458d3dc7ee26
