### ISSUE TITLE
Update seq-tools to support nested CRAM info check

### ISSUE THREAD

**Issue by edsu7** [icgc-argo/argo-data-submission#40]
Given the example :
```
  "files": [
    {
      "fileName": "anon_chr1_completeA.bam",
      "fileSize": 269442,
      "fileMd5sum": "968711f781f217dfb1de630e520ccacb",
      "fileType": "BAM",
      "fileAccess": "controlled",
      "dataType": "Submitted Reads",
      "info": {
        "data_category": "Sequencing Reads",
        "original_cram_info": {
          "fileName": "anon_chr1_completeA.cram",
          "fileSize": 132507,
          "fileMd5sum": "0d1776d44d8da87758d6b159aa8e6bc5",
          "fileType": "CRAM",
          "referenceFileName": "hs73d5.fa.gz"
        }
      }
    }
```
Seq-tools currently only checks `files[0][fileSize]` and `files[0][fileMd5sum]`. 
For `CRAM` files that have their original info nested and converted version is auto-populates `files[0][fileSize]` and `files[0][fileMd5sum]` .
This potentially allows a submitter to submit incorrect CRAM info and bypass `md5sum` and `fileSize` checks.

- [ ] Update Seq-tools
- [ ] Release updated seq-tools version
- [ ] Update Seq-tools WFPM module

**Comment by puneet-oicr** [comment]
All PRs approved. Merge to Seq-Tools pending next

**Comment by b-f-chan** [comment]
Merged, closing
