### ISSUE TITLE
Feature Request - add step to generate receipt for successful submission

### ISSUE THREAD

**Issue by lindaxiang** [icgc-argo/argo-data-submission#52]

**Comment by edsu7** [comment]
Feedback from `MUTO-INTL`, they hope to see a "receipt" or acknowledgement of successful data submission.

Their attempts at submission using `score`/`song` were successful but the tools did not convey the submission worked. This resulted in `MUTO-INTL` relying on the dashboard which also had problems displaying correct results. These situations compounded resulting in the data submitters submitting multiple copies of the same file.

While the data submission workflow does log and generate a payload, this step will generate a receipt and output said receipt will help user acknowledge data upload was successful.

**Comment by puneet-oicr** [comment]
Feedback from Linda. Edmund to work on changes.
