### ISSUE TITLE
Fix Docker - Mount Song/Score log folder to container work folder  

### ISSUE THREAD

**Issue by puneet-oicr** [icgc-argo/argo-data-submission#54]

**Comment by edsu7** [comment]
PR started:
https://github.com/icgc-argo-workflows/nextflow-data-processing-utility-tools/pull/49

**Comment by b-f-chan** [comment]
@lindaxiang has provided more feedback, but for now @edsu7 will merge what he has for now and address feedback later.  Song/Score should be changed, @edsu7 to create separate ticket for this.

**Comment by b-f-chan** [comment]
Actually incorrect settings were being passed into the client, which is what caused this issue, once settings were corrected, this no longer occurs, so PR has been merged, closing ticket
