### ISSUE TITLE
Add params `--force` to let the song-score-upload to overwrite the previously uploaded objects

### ISSUE THREAD

**Issue by lindaxiang** [icgc-argo/argo-data-submission#74]
Context:
Feature request from MUTO-INTL, there was a failed upload due to score-client version. After upgrade the score-client version, they will need to use score's `--force` params to overwrite the existing uploaded objects.

The submission workflow and song-score-upload subworkflow need to expose that param in order to support the feature.

**Comment by lindaxiang** [comment]
This has been addressed by PR: https://github.com/icgc-argo-workflows/nextflow-data-processing-utility-tools/pull/53

**Comment by justincorrigible** [comment]
Closing as completed.
