### ISSUE TITLE
Score parameters not being passed correctly

### ISSUE THREAD

**Issue by edsu7** [icgc-argo/argo-data-submission#75]
CPUs and memory are not being passed into score b/c the correct variables are not being set:
https://github.com/icgc-argo/argo-data-submission/blob/main/argo-data-submission-wf/main.nf#L129-L142

## Possible Implementation
```
  'score_transport_mem' : params.mem,
  'score_mem' : params.mem,
  'score_cpus': params.cpus,
  'song_mem' : params.mem,
  'song_cpus': params.cpus,
```

**Comment by justincorrigible** [comment]
closing as completed

**Comment by justincorrigible** [comment]
closing as completed
