### ISSUE TITLE
Update data submission workflow to reflect the dictionary changes in `experiment`

### ISSUE THREAD

**Issue by lindaxiang** [icgc-argo/argo-data-submission#78]

**Comment by edsu7** [comment]
experiment_schema updated:
https://github.com/icgc-argo/argo-metadata-schemas/pull/73
Added into QA submission.song : 
https://submission-song.rdpc-qa.cancercollaboratory.org/schemas/sequencing_experiment?unrenderedOnly=false&version=10

**Comment by edsu7** [comment]
[PR](https://github.com/icgc-argo/argo-data-submission/pull/80) made to support JSONs with target-seq fields to TSVs
[PR](https://github.com/icgc-argo-workflows/data-processing-utility-tools/pull/169) merged to support TSVs with target-seq fields to JSON

**Comment by edsu7** [comment]
Merged.Closing.
